import { TransactionStatus, type Transaction } from "./types";

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "TRX-882910",
    date: "Oct 24, 2023",
    merchant: "Amazon Web Services",
    description: "Cloud Infrastructure",
    amount: -4290.55,
    category: "Operational",
    status: TransactionStatus.COMPLETED,
    icon: "Cloud",
  },
  {
    id: "TRX-882909",
    date: "Oct 23, 2023",
    merchant: "Wework Offices",
    description: "Real Estate / Rent",
    amount: -12400.0,
    category: "Facility",
    status: TransactionStatus.PENDING,
    icon: "Building2",
  },
  {
    id: "TRX-882898",
    date: "Oct 21, 2023",
    merchant: "United Airlines",
    description: "Business Travel",
    amount: -1240.2,
    category: "Logistics",
    status: TransactionStatus.CANCELLED,
    icon: "Plane",
  },
  {
    id: "TRX-882890",
    date: "Oct 19, 2023",
    merchant: "Slack Technologies",
    description: "Communications Software",
    amount: -850.0,
    category: "Operational",
    status: TransactionStatus.COMPLETED,
    icon: "MessageSquare",
  },
  {
    id: "TRX-882885",
    date: "Oct 18, 2023",
    merchant: "Apple Inc.",
    description: "Hardware Procurement",
    amount: -25400.0,
    category: "Asset",
    status: TransactionStatus.COMPLETED,
    icon: "Laptop",
  },
];
