/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import type { Transaction, Budget } from "./types";

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    date: "Oct 24, 2023",
    time: "14:32 PM",
    description: "Steel Siding Bulk Purchase",
    refId: "REF-92834710-X",
    category: "Procurement",
    amount: -12450.0,
    overSpending: "Critical",
    status: "Completed",
    icon: "building",
  },
  {
    id: "tx-2",
    date: "Oct 23, 2023",
    time: "09:15 AM",
    description: "Consultation Fee - Q4",
    refId: "REF-00234123-A",
    category: "Revenue",
    amount: 4200.0,
    overSpending: "Fine",
    status: "Completed",
    icon: "payment",
  },
  {
    id: "tx-3",
    date: "Oct 21, 2023",
    time: "16:45 PM",
    description: "Infrastructure Maintenance",
    refId: "REF-11223344-Z",
    category: "Maintenance",
    amount: -2150.75,
    overSpending: "Warning",
    status: "Pending",
    icon: "maintenance",
  },
  {
    id: "tx-4",
    date: "Oct 19, 2023",
    time: "11:20 AM",
    description: "AWS Enterprise Subscription",
    refId: "REF-88776655-Q",
    category: "Infrastructure",
    amount: -850.0,
    overSpending: "Fine",
    status: "Failed",
    icon: "cloud",
  },
  {
    id: "tx-5",
    date: "Oct 18, 2023",
    time: "10:00 AM",
    description: "Payroll Disbursement - Marketing",
    refId: "REF-55443322-B",
    category: "HR & Payroll",
    amount: -45000.0,
    overSpending: "Critical",
    status: "Completed",
    icon: "payroll",
  },
  {
    id: "tx-6",
    date: "Oct 15, 2023",
    time: "15:22 PM",
    description: "Concrete Foundation Raw Mix",
    refId: "REF-44930192-K",
    category: "Procurement",
    amount: -8900.0,
    overSpending: "Warning",
    status: "Completed",
    icon: "building",
  },
  {
    id: "tx-7",
    date: "Oct 14, 2023",
    time: "08:30 AM",
    description: "Architect License Renewal",
    refId: "REF-11234910-Y",
    category: "Infrastructure",
    amount: -1200.0,
    overSpending: "Fine",
    status: "Completed",
    icon: "maintenance",
  },
  {
    id: "tx-8",
    date: "Oct 10, 2023",
    time: "17:00 PM",
    description: "Client Premium Retainer",
    refId: "REF-55410928-V",
    category: "Revenue",
    amount: 15400.0,
    overSpending: "Fine",
    status: "Completed",
    icon: "payment",
  },
  {
    id: "tx-9",
    date: "Oct 08, 2023",
    time: "12:00 PM",
    description: "Figma Enterprise License",
    refId: "REF-77625102-L",
    category: "Infrastructure",
    amount: -450.0,
    overSpending: "Fine",
    status: "Completed",
    icon: "cloud",
  },
  {
    id: "tx-10",
    date: "Oct 05, 2023",
    time: "09:40 AM",
    description: "Structural Engineer Consultation",
    refId: "REF-00923841-M",
    category: "Procurement",
    amount: -3200.0,
    overSpending: "Warning",
    status: "Completed",
    icon: "building",
  },
  {
    id: "tx-11",
    date: "Sep 28, 2023",
    time: "14:15 PM",
    description: "Office Server Upgrades",
    refId: "REF-83940192-P",
    category: "Infrastructure",
    amount: -5400.0,
    overSpending: "Warning",
    status: "Completed",
    icon: "cloud",
  },
  {
    id: "tx-12",
    date: "Sep 25, 2023",
    time: "11:00 AM",
    description: "Government Permit Submission",
    refId: "REF-10293847-G",
    category: "Infrastructure",
    amount: -750.0,
    overSpending: "Fine",
    status: "Completed",
    icon: "maintenance",
  },
  {
    id: "tx-13",
    date: "Sep 20, 2023",
    time: "10:00 AM",
    description: "Bi-Weekly Contractor Payroll",
    refId: "REF-44930182-C",
    category: "HR & Payroll",
    amount: -38000.0,
    overSpending: "Critical",
    status: "Completed",
    icon: "payroll",
  },
  {
    id: "tx-14",
    date: "Sep 15, 2023",
    time: "16:00 PM",
    description: "Interior Design Retainer Q3",
    refId: "REF-88771122-D",
    category: "Revenue",
    amount: 12500.0,
    overSpending: "Fine",
    status: "Completed",
    icon: "payment",
  },
];

export const INITIAL_BUDGET_DATA: Budget[] = [
  {
    category: "Procurement",
    allocated: 50000,
    spent: 34550,
    color: "from-blue-600 to-blue-800",
  },
  {
    category: "Infrastructure",
    allocated: 15000,
    spent: 8650,
    color: "from-teal-600 to-teal-800",
  },
  {
    category: "Maintenance",
    allocated: 12000,
    spent: 3350,
    color: "from-amber-600 to-amber-800",
  },
  {
    category: "HR & Payroll",
    allocated: 100000,
    spent: 83000,
    color: "from-purple-600 to-purple-800",
  },
  {
    category: "Marketing & Other",
    allocated: 20000,
    spent: 15400,
    color: "from-slate-600 to-slate-800",
  },
];

export const CATEGORIES = [
  "All Categories",
  "Procurement",
  "Revenue",
  "Maintenance",
  "Infrastructure",
  "HR & Payroll",
];

export const STATUSES = ["All Status", "Completed", "Pending", "Failed"];
