import type { Debt } from './types';

export const INITIAL_DEBTS: Debt[] = [
  {
    id: 'debt-1',
    dateCreated: '12/05/2024',
    creditor: 'Vietcombank Corporate',
    creditorType: 'bank',
    referenceCode: 'INV-2024-0891',
    amount: 450000000,
    dueDate: '10/06/2024',
    status: 'Critical',
    description: 'Khoản thanh toán tín dụng doanh nghiệp quý II.',
    notes: 'Liên hệ nhân viên tín dụng: Trần Hoàng Nam (Ext: 104).'
  },
  {
    id: 'debt-2',
    dateCreated: '15/05/2024',
    creditor: 'Tech-Flow Solutions',
    creditorType: 'tech',
    referenceCode: 'BILL-X92-A',
    amount: 1200000000,
    dueDate: '25/06/2024',
    status: 'Warning',
    description: 'Hợp đồng phát triển hệ thống Cloud ERP giai đoạn 3.',
    notes: 'Phí phạt trễ hạn được tính 1.5% sau ngày 25/06.'
  },
  {
    id: 'debt-3',
    dateCreated: '20/05/2024',
    creditor: 'Lighthouse Real Estate',
    creditorType: 'real_estate',
    referenceCode: 'RENT-05-24',
    amount: 850000000,
    dueDate: '01/07/2024',
    status: 'Fine',
    description: 'Tiền thuê mặt bằng văn phòng trụ sở chính tháng 5.',
    notes: 'Đã nhận hóa đơn VAT ngày 22/05.'
  },
  {
    id: 'debt-4',
    dateCreated: '22/05/2024',
    creditor: 'Tân Phát Logistics',
    creditorType: 'logistics',
    referenceCode: 'LOG-TP-552',
    amount: 322500000,
    dueDate: '15/07/2024',
    status: 'Fine',
    description: 'Chi phí vận chuyển và thông quan lô hàng linh kiện điện tử.',
    notes: 'Đội trưởng kho xác nhận đã nhận đủ hàng và chứng từ.'
  },
  {
    id: 'debt-5',
    dateCreated: '05/05/2024',
    creditor: 'Vinamilk Distribution',
    creditorType: 'other',
    referenceCode: 'VM-991A',
    amount: 150000000,
    dueDate: '30/05/2024',
    status: 'Paid',
    description: 'Thanh toán đơn hàng FMCG tháng 4.',
    notes: 'Đã hoàn tất chuyển khoản nông nghiệp số tham chiếu VCB-77312.'
  },
  {
    id: 'debt-6',
    dateCreated: '18/05/2024',
    creditor: 'FPT Software Center',
    creditorType: 'tech',
    referenceCode: 'FPT-CLOUD-10',
    amount: 95000000,
    dueDate: '20/06/2024',
    status: 'Fine',
    description: 'Phí bản quyền Cloud Services cho các chi nhánh miền Nam.',
    notes: 'Hạn mức sử dụng 400 người dùng.'
  },
  {
    id: 'debt-7',
    dateCreated: '02/05/2024',
    creditor: 'BIDV Commercial',
    creditorType: 'bank',
    referenceCode: 'LN-BIDV-844',
    amount: 2500000000,
    dueDate: '15/05/2024',
    status: 'Paid',
    description: 'Gói vay lưu động bổ sung vốn điều lệ.',
    notes: 'Tất toán trước thời hạn.'
  },
  {
    id: 'debt-8',
    dateCreated: '24/05/2024',
    creditor: 'Công trình Đô thị SG',
    creditorType: 'real_estate',
    referenceCode: 'CON-DSG-445',
    amount: 210000000,
    dueDate: '05/06/2024',
    status: 'Critical',
    description: 'Phí bảo dưỡng và thi công cải tạo cảnh quan tầng bệt.',
    notes: 'Đơn vị thi công đang hối thúc chuyển khoản.'
  },
  {
    id: 'debt-9',
    dateCreated: '25/05/2024',
    creditor: 'Hòa Phát Steel Corp',
    creditorType: 'other',
    referenceCode: 'HP-IRON-222',
    amount: 670000000,
    dueDate: '10/07/2024',
    status: 'Warning',
    description: 'Cung cấp thép xây dựng dự án nhà kho Thủ Đức.',
    notes: 'Thanh toán đợt 1 theo tỷ lệ 30%.'
  },
  {
    id: 'debt-10',
    dateCreated: '10/05/2024',
    creditor: 'Intel Vietnam Logistics',
    creditorType: 'logistics',
    referenceCode: 'INV-ITL-491',
    amount: 180000000,
    dueDate: '12/06/2024',
    status: 'Paid',
    description: 'Phí bảo hiểm vận tải quốc tế đường hàng không.',
    notes: 'Giấy báo nợ số 449102.'
  },
  {
    id: 'debt-11',
    dateCreated: '26/05/2024',
    creditor: 'ACB Bank Corporate',
    creditorType: 'bank',
    referenceCode: 'ACB-TERM-02',
    amount: 350000000,
    dueDate: '14/06/2024',
    status: 'Warning',
    description: 'Thanh toán lãi định kỳ trái phiếu ACB-2024.',
    notes: 'Yêu cầu chuyển trước 16h00 của ngày đáo hạn.'
  },
  {
    id: 'debt-12',
    dateCreated: '27/05/2024',
    creditor: 'Viettel Telecom',
    creditorType: 'tech',
    referenceCode: 'VTT-NET-852',
    amount: 45000000,
    dueDate: '30/06/2024',
    status: 'Fine',
    description: 'Hợp đồng cáp quang kênh thuê riêng Leased Line 1Gbps.',
    notes: 'Phòng IT nghiệm thu chất lượng dịch vụ đạt 99.99%.'
  },
  {
    id: 'debt-13',
    dateCreated: '28/05/2024',
    creditor: 'Bình Tân Packaging',
    creditorType: 'other',
    referenceCode: 'PKG-BT-902',
    amount: 110000000,
    dueDate: '08/07/2024',
    status: 'Fine',
    description: 'In ấn bao bì mẫu mã dòng sản phẩm sữa dinh dưỡng mới.',
    notes: 'Bàn giao hoàn tất tại tổng kho Bình Dương.'
  },
  {
    id: 'debt-14',
    dateCreated: '01/05/2024',
    creditor: 'Vietcombank Corporate',
    creditorType: 'bank',
    referenceCode: 'INV-2024-0700',
    amount: 500000000,
    dueDate: '20/05/2024',
    status: 'Paid',
    description: 'Ký quỹ bảo lãnh gói đầu tư cơ sở hạ tầng.',
    notes: 'Tiền đã được khớp và hoàn trả ký quỹ.'
  },
  {
    id: 'debt-15',
    dateCreated: '29/05/2024',
    creditor: 'Thế Giới Di Động Business',
    creditorType: 'other',
    referenceCode: 'MWG-DEV-411',
    amount: 145000000,
    dueDate: '11/06/2024',
    status: 'Warning',
    description: 'Cung cấp 30 thiết bị iPad Pro cho đội ngũ nhân viên thị trường.',
    notes: 'Kèm gói bảo hành VIP 2 năm.'
  },
  {
    id: 'debt-16',
    dateCreated: '30/05/2024',
    creditor: 'CMC Telecom',
    creditorType: 'tech',
    referenceCode: 'CMC-DC-901',
    amount: 80000000,
    dueDate: '05/07/2024',
    status: 'Fine',
    description: 'Thuê chỗ đặt tủ Rack máy chủ tại Data Center Tân Thuận.',
    notes: 'Thời hạn hợp đồng tiếp tục gia hạn thêm 12 tháng.'
  },
  {
    id: 'debt-17',
    dateCreated: '11/05/2024',
    creditor: 'Phát Đạt Realtor',
    creditorType: 'real_estate',
    referenceCode: 'PDR-LAND-881',
    amount: 1550000000,
    dueDate: '10/06/2024',
    status: 'Critical',
    description: 'Tiền cọc mua văn phòng đại diện Quận 3 đợt cuối.',
    notes: 'Có nguy cơ mất cọc nếu trễ hạn quá 5 ngày làm việc.'
  },
  {
    id: 'debt-18',
    dateCreated: '02/06/2024',
    creditor: 'Sotrans Logistics',
    creditorType: 'logistics',
    referenceCode: 'SOT-SEA-112',
    amount: 220000000,
    dueDate: '28/06/2024',
    status: 'Fine',
    description: 'Vận chuyển container hàng lạnh cập cảng Cát Lái.',
    notes: 'Hải quan đã ký thông quan thông thường.'
  },
  {
    id: 'debt-19',
    dateCreated: '03/06/2024',
    creditor: 'Giao Hàng Nhanh (GHN)',
    creditorType: 'logistics',
    referenceCode: 'GHN-COD-990',
    amount: 65000000,
    dueDate: '17/06/2024',
    status: 'Paid',
    description: 'Đối soát thu hộ COD tuần cuối tháng 5.',
    notes: 'Kế toán đối khớp không có chênh lệch.'
  },
  {
    id: 'debt-20',
    dateCreated: '04/06/2024',
    creditor: 'Vingroup Office Space',
    creditorType: 'real_estate',
    referenceCode: 'VIN-RE-229',
    amount: 320000000,
    dueDate: '20/07/2024',
    status: 'Fine',
    description: 'Phí dịch vụ vận hành và điện nước tòa chung cư dịch vụ.',
    notes: 'Hóa đơn đã xuất đầy đủ vào hòm thư tài chính.'
  },
  {
    id: 'debt-21',
    dateCreated: '05/06/2024',
    creditor: 'VietinBank Finance',
    creditorType: 'bank',
    referenceCode: 'VTB-DEBT-099',
    amount: 1800000000,
    dueDate: '08/07/2024',
    status: 'Fine',
    description: 'Gói giải ngân tín dụng thiết bị dây chuyền đóng gói chai.',
    notes: 'Bảo lãnh bằng tài sản máy móc thiết bị nhập khẩu.'
  },
  {
    id: 'debt-22',
    dateCreated: '06/06/2024',
    creditor: 'Mắt Bão Corporation',
    creditorType: 'tech',
    referenceCode: 'MB-DOM-771',
    amount: 12500000,
    dueDate: '20/06/2024',
    status: 'Paid',
    description: 'Gia hạn tên miền toàn quốc và dịch vụ email server.',
    notes: 'Tự động thanh toán qua thẻ VISA doanh nghiệp.'
  },
  {
    id: 'debt-23',
    dateCreated: '07/06/2024',
    creditor: 'Hòa Bình Construction',
    creditorType: 'real_estate',
    referenceCode: 'HBC-BLD-811',
    amount: 1400000000,
    dueDate: '15/07/2024',
    status: 'Warning',
    description: 'Xây dựng nhà xưởng chứa nguyên vật liệu số 2 Hải Phòng.',
    notes: 'Nghiệm thu dầm móng và cột trụ chính đợt 2.'
  },
  {
    id: 'debt-24',
    dateCreated: '08/06/2024',
    creditor: 'GrabExpress Vietnam',
    creditorType: 'logistics',
    referenceCode: 'GRB-DEL-104',
    amount: 18500000,
    dueDate: '22/06/2024',
    status: 'Paid',
    description: 'Chi phí di chuyển công tác bưu kiện nội thành toàn quốc tháng 5.',
    notes: 'Đã thanh toán ví Grab for Business.'
  }
];
